# **IMPORTS**

In [1]:
from scipy.io import loadmat
import numpy as np
import pandas as pd

# **DATA PREPERATION**

In [2]:
mat = loadmat('vote.mat')
mat

{'__header__': b'MATLAB 5.0 MAT-file, Platform: PCWIN, Created on: Sat Oct 17 14:20:37 2015',
 '__version__': '1.0',
 '__globals__': [],
 'Data': array([[1, 0, 1, ..., 0, 1, 1],
        [0, 0, 1, ..., 0, 1, 0],
        [1, 1, 0, ..., 0, 1, 0],
        ...,
        [0, 1, 1, ..., 1, 1, 1],
        [1, 0, 1, ..., 1, 1, 1],
        [1, 0, 1, ..., 0, 1, 1]], shape=(325, 17), dtype=uint8)}

In [3]:
print(mat.keys())

dict_keys(['__header__', '__version__', '__globals__', 'Data'])


In [4]:
Data = mat['Data']
Data

array([[1, 0, 1, ..., 0, 1, 1],
       [0, 0, 1, ..., 0, 1, 0],
       [1, 1, 0, ..., 0, 1, 0],
       ...,
       [0, 1, 1, ..., 1, 1, 1],
       [1, 0, 1, ..., 1, 1, 1],
       [1, 0, 1, ..., 0, 1, 1]], shape=(325, 17), dtype=uint8)

In [5]:
feature_names = [
    "HANDICAPPED_INFANTS",
    "WATER_PROJECT_COST_SHARING",
    "ADOPTION_OF_BUDGET_RESOLUTION",
    "PHYSICIAN_FEE_FREEZE",
    "EL_SALVADOR_AID",
    "RELIGIOUS_GROUPS_IN_SCHOOLS",
    "ANTI_SATELLITE_TEST_BAN",
    "AID_TO_NICARAGUAN_CONTRAS",
    "MX_MISSILE",
    "IMMIGRATION",
    "SYNFUELS_CORPORATION_CUTBACK",
    "EDUCATION_SPENDING",
    "SUPERFUND_RIGHT_TO_SUE",
    "CRIME",
    "DUTY_FREE_EXPORTS",
    "EXPORT_ADMINISTRATION_ACT_SOUTH_AFRICA"
]

In [6]:
# First 16 columns : Features
# Last column      : Class Label
X = Data[:, :16]
y = Data[:, 16]

In [7]:
X

array([[1, 0, 1, ..., 1, 0, 1],
       [0, 0, 1, ..., 1, 0, 1],
       [1, 1, 0, ..., 1, 0, 1],
       ...,
       [0, 1, 1, ..., 0, 1, 1],
       [1, 0, 1, ..., 0, 1, 1],
       [1, 0, 1, ..., 1, 0, 1]], shape=(325, 16), dtype=uint8)

In [8]:
y 
# Democrat   = 1
# Republican = 0

array([1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0,
       1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1,
       0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1,
       1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1,
       0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1,

# **NAIVE BAYES**

## Train Bernoulli Naive Bayes

In [9]:
def train_naive_bayes(X_train, y_train):

    # Prior probabilities
    p_democrat = np.mean(y_train == 1)
    p_republican = np.mean(y_train == 0)

    # Laplace smoothing
    alpha = (
        np.sum(X_train[y_train == 1], axis=0) + 1
    ) / (
        np.sum(y_train == 1) + 2
    )

    beta = (
        np.sum(X_train[y_train == 0], axis=0) + 1
    ) / (
        np.sum(y_train == 0) + 2
    )

    return p_democrat, p_republican, alpha, beta

## Prediction

In [10]:
def predict_naive_bayes(X_test,
                        p_democrat,
                        p_republican,
                        alpha,
                        beta):

    predictions = []

    for x in X_test:

        log_democrat = np.log(p_democrat)
        log_republican = np.log(p_republican)

        log_democrat += np.sum(
            x * np.log(alpha)
            + (1 - x) * np.log(1 - alpha)
        )

        log_republican += np.sum(
            x * np.log(beta)
            + (1 - x) * np.log(1 - beta)
        )

        if log_democrat >= log_republican:
            predictions.append(1)
        else:
            predictions.append(0)

    return np.array(predictions)

# **EVALUATION METRICS**

In [11]:
def confusion_matrix_binary(y_true, y_pred):

    TP = np.sum((y_true == 1) & (y_pred == 1))
    TN = np.sum((y_true == 0) & (y_pred == 0))
    FP = np.sum((y_true == 0) & (y_pred == 1))
    FN = np.sum((y_true == 1) & (y_pred == 0))

    return TP, TN, FP, FN

# **CROSS VALIDATION**

## 5-Fold Cross Validation

In [12]:
fold_size = 65

errors = []
accuracies = []
precisions = []
recalls = []

print("=" * 80)
print("5-FOLD CROSS VALIDATION RESULTS")
print("=" * 80)

for fold in range(5):

    start = fold * fold_size
    end = start + fold_size

    X_test = X[start:end]
    y_test = y[start:end]

    X_train = np.concatenate(
        [X[:start], X[end:]],
        axis=0
    )

    y_train = np.concatenate(
        [y[:start], y[end:]]
    )

    p_democrat, p_republican, alpha, beta = \
        train_naive_bayes(X_train, y_train)

    y_pred = predict_naive_bayes(
        X_test,
        p_democrat,
        p_republican,
        alpha,
        beta
    )

    TP, TN, FP, FN = \
        confusion_matrix_binary(y_test, y_pred)

    accuracy = (TP + TN) / len(y_test)
    error = 1 - accuracy

    precision = TP / (TP + FP) \
        if (TP + FP) > 0 else 0

    recall = TP / (TP + FN) \
        if (TP + FN) > 0 else 0

    accuracies.append(accuracy)
    errors.append(error)
    precisions.append(precision)
    recalls.append(recall)

    print("\n")
    print("-" * 80)
    print(f"FOLD {fold+1}")
    print("-" * 80)

    print(f"Training Samples : {len(X_train)}")
    print(f"Testing Samples  : {len(X_test)}")

    print("\nConfusion Matrix")
    print(f"TP = {TP}")
    print(f"TN = {TN}")
    print(f"FP = {FP}")
    print(f"FN = {FN}")

    print("\nPerformance")
    print(f"Accuracy  = {accuracy*100:.2f}%")
    print(f"Error     = {error*100:.2f}%")
    print(f"Precision = {precision*100:.2f}%")
    print(f"Recall    = {recall*100:.2f}%")

5-FOLD CROSS VALIDATION RESULTS


--------------------------------------------------------------------------------
FOLD 1
--------------------------------------------------------------------------------
Training Samples : 260
Testing Samples  : 65

Confusion Matrix
TP = 30
TN = 27
FP = 1
FN = 7

Performance
Accuracy  = 87.69%
Error     = 12.31%
Precision = 96.77%
Recall    = 81.08%


--------------------------------------------------------------------------------
FOLD 2
--------------------------------------------------------------------------------
Training Samples : 260
Testing Samples  : 65

Confusion Matrix
TP = 42
TN = 19
FP = 1
FN = 3

Performance
Accuracy  = 93.85%
Error     = 6.15%
Precision = 97.67%
Recall    = 93.33%


--------------------------------------------------------------------------------
FOLD 3
--------------------------------------------------------------------------------
Training Samples : 260
Testing Samples  : 65

Confusion Matrix
TP = 37
TN = 21
FP = 2
FN = 5

## Overall Cross Validation Result

In [13]:
print("\n")
print("=" * 80)
print("OVERALL CROSS VALIDATION RESULT")
print("=" * 80)

for i in range(5):

    print(
        f"Fold {i+1}: "
        f"Accuracy={accuracies[i]*100:.2f}% , "
        f"Error={errors[i]*100:.2f}%"
    )

print("\nAverage Results")

print(f"Average Accuracy  = {np.mean(accuracies)*100:.2f}%")
print(f"Average Error     = {np.mean(errors)*100:.2f}%")
print(f"Average Precision = {np.mean(precisions)*100:.2f}%")
print(f"Average Recall    = {np.mean(recalls)*100:.2f}%")



OVERALL CROSS VALIDATION RESULT
Fold 1: Accuracy=87.69% , Error=12.31%
Fold 2: Accuracy=93.85% , Error=6.15%
Fold 3: Accuracy=89.23% , Error=10.77%
Fold 4: Accuracy=90.77% , Error=9.23%
Fold 5: Accuracy=87.69% , Error=12.31%

Average Results
Average Accuracy  = 89.85%
Average Error     = 10.15%
Average Precision = 95.89%
Average Recall    = 87.94%


# **FEATURE ANALYSIS**

## Train On Full Dataset For Feature Analysis

In [14]:
p_democrat, p_republican, alpha, beta = \
    train_naive_bayes(X, y)

# Weight formula from lecture slides

weights = (
    np.log(alpha / (1 - alpha))
    -
    np.log(beta / (1 - beta))
)

tendency = []

for w in weights:

    if w > 0:
        tendency.append("Democrat")

    elif w < 0:
        tendency.append("Republican")

    else:
        tendency.append("Neutral")

## Feature Analysis Table

In [15]:
feature_table = pd.DataFrame({

    "Feature": feature_names,

    "Alpha=P(x=1|Democrat)": alpha,

    "Beta=P(x=1|Republican)": beta,

    "Weight": weights,

    "AbsWeight": np.abs(weights),

    "Tendency": tendency

})

# **PRINT RESULTS**

## Original Order

In [16]:
print("\n")
print("=" * 120)
print("FEATURE ANALYSIS (ORIGINAL ORDER)")
print("=" * 120)

print(feature_table.to_string(index=False))




FEATURE ANALYSIS (ORIGINAL ORDER)
                               Feature  Alpha=P(x=1|Democrat)  Beta=P(x=1|Republican)    Weight  AbsWeight   Tendency
                   HANDICAPPED_INFANTS               0.591549                0.275862  1.335455   1.335455   Democrat
            WATER_PROJECT_COST_SHARING               0.535211                0.560345 -0.101483   0.101483 Republican
         ADOPTION_OF_BUDGET_RESOLUTION               0.863850                0.198276  3.244745   3.244745   Democrat
                  PHYSICIAN_FEE_FREEZE               0.065728                0.974138 -6.283023   6.283023 Republican
                       EL_SALVADOR_AID               0.258216                0.922414 -3.530866   3.530866 Republican
           RELIGIOUS_GROUPS_IN_SCHOOLS               0.549296                0.844828 -1.496770   1.496770 Republican
               ANTI_SATELLITE_TEST_BAN               0.723005                0.336207  1.639659   1.639659   Democrat
             AID_TO_

## Ranking By Importance

In [17]:
ranking = feature_table.sort_values(
    by="AbsWeight",
    ascending=False
)

print("\n")
print("=" * 120)
print("FEATURE IMPORTANCE RANKING")
print("=" * 120)

print(
    ranking[
        [
            "Feature",
            "Weight",
            "AbsWeight",
            "Tendency"
        ]
    ].to_string(index=False)
)



FEATURE IMPORTANCE RANKING
                               Feature    Weight  AbsWeight   Tendency
                  PHYSICIAN_FEE_FREEZE -6.283023   6.283023 Republican
                                 CRIME -3.702578   3.702578 Republican
                       EL_SALVADOR_AID -3.530866   3.530866 Republican
         ADOPTION_OF_BUDGET_RESOLUTION  3.244745   3.244745   Democrat
                    EDUCATION_SPENDING -3.128182   3.128182 Republican
             AID_TO_NICARAGUAN_CONTRAS  2.661036   2.661036   Democrat
                            MX_MISSILE  2.566365   2.566365   Democrat
                     DUTY_FREE_EXPORTS  2.355764   2.355764   Democrat
                SUPERFUND_RIGHT_TO_SUE -2.282965   2.282965 Republican
          SYNFUELS_CORPORATION_CUTBACK  1.779153   1.779153   Democrat
               ANTI_SATELLITE_TEST_BAN  1.639659   1.639659   Democrat
           RELIGIOUS_GROUPS_IN_SCHOOLS -1.496770   1.496770 Republican
                   HANDICAPPED_INFANTS  1.335455

## Top 5 Most Important Features

In [18]:
print("\n")
print("=" * 120)
print("TOP 5 MOST IMPORTANT FEATURES")
print("=" * 120)

print(
    ranking[
        [
            "Feature",
            "Weight",
            "Tendency"
        ]
    ].head(5).to_string(index=False)
)



TOP 5 MOST IMPORTANT FEATURES
                      Feature    Weight   Tendency
         PHYSICIAN_FEE_FREEZE -6.283023 Republican
                        CRIME -3.702578 Republican
              EL_SALVADOR_AID -3.530866 Republican
ADOPTION_OF_BUDGET_RESOLUTION  3.244745   Democrat
           EDUCATION_SPENDING -3.128182 Republican
